INSERT INTO SERVICE (Vehicle_type,Service_name,Labor)
VALUES 
        ('Sedan', 'Oil Change', 75),
        ('Sedan', 'Front end alignments', 20 ),
        ('Sedan', 'Brakes', 40),
        ('Sedan', 'Tire repair and replacement', 40), 
        ('Sedan', 'Engine tune ups', 60), 
        ('Sedan', 'Vehicle computer diagnostics', 30), 
        ('Sedan', 'State Vehicle Inspections', 20), 
        ('SUV', 'Oil Change', 8), 
        ('SUV', 'Front end alignments', 30), 
        ('SUV', 'Brakes', 50), 
        ('SUV', 'Tire repair and replacement', 50), 
        ('SUV', 'Engine tune ups', 70), 
        ('SUV', 'Vehicle computer diagnostics', 40), 
        ('SUV', 'State Vehicle Inspections', 30), 
        ('Sports', 'Oil Change', 95), 
        ('Sports', 'Front end alignments', 40), 
        ('Sports', 'Brakes', 60), 
        ('Sports', 'Tire repair and replacement', 60), 
        ('Sports', 'Engine tune ups', 80), 
        ('Sports', 'Vehicle computer diagnostics', 50), 
        ('Sports', 'State Vehicle Inspections', 40), 
        ('Truck', 'Oil Change', 85), 
        ('Truck', 'Front end alignments', 30), 
        ('Truck', 'Brakes', 60), 
        ('Truck', 'Tire repair and replacement', 60), 
        ('Truck', 'Engine tune ups', 90), 
        ('Truck', 'Vehicle computer diagnostics', 35), 
        ('Truck', 'State Vehicle Inspections', 40);
