INSERT INTO SERVICE (Vehicle_type, Service_name ,Labor, Price, Skill_ID) VALUES
('Sedan', 'Oil Change', 75,NULL, NULL),
('Sedan', 'Front end alignments', 20 ,NULL, NULL ),
('Sedan', 'Brakes', 40, NULL, NULL),
('Sedan', 'Tire repair and replacement', 40,NULL, NULL),
('Sedan', 'Engine tune ups', 60, NULL, NULL),
('Sedan', 'Vehicle computer diagnostics', 30 , NULL , NULL),
('Sedan', 'State Vehicle Inspections', 20, NULL, NULL),
('SUV', 'Oil Change', 85, NULL, NULL),
('SUV', 'Front end alignments', 30, NULL , NULL),
('SUV', 'Brakes', 50, NULL, NULL),
('SUV', 'Tire repair and replacement', 50, NULL, NULL),
('SUV', 'Engine tune ups', 70, NULL, NULL),
('SUV', 'Vehicle computer diagnostics', 40, NULL, NULL),
('SUV', 'State Vehicle Inspections', 30, NULL, NULL),
('Sports', 'Oil Change', 95, NULL, NULL),
('Sports', 'Front end alignments', 40 , NULL, NULL),
('Sports', 'Brakes', 60, NULL, NULL),
('Sports', 'Vehicle computer diagnostics', 50 , NULL , NULL),
('Sports', 'Tire repair and replacement', 60, NULL, NULL),
('Sports', 'Engine tune ups', 80, NULL, NULL),
('Sports', 'State Vehicle Inspections', 40, NULL, NULL),
('Truck', 'Oil Change', 85, NULL, NULL),
('Truck', 'Front end alignments', 30 , NULL, NULL),
('Truck', 'Brakes', 60, NULL, NULL),
('Truck', 'Tire repair and replacement', 60, NULL, NULL),
('Truck', 'Engine tune ups', 90, NULL, NULL),
('Truck', 'Vehicle computer diagnostics', 35 , NULL, NULL),
('Truck', 'State Vehicle Inspections', 40, NULL, NULL);
